package com.example.wsa.contact;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import java.time.LocalDate;

// Mark the class as a data class using the @Data annotation
@Data
@NoArgsConstructor
// Generate an all-args constructor using the @AllArgsConstructor annotation
@AllArgsConstructor
public class Contact {

    // Define private fields for com.example.wsa.contact information
    private Integer id;       // Unique identifier for the com.example.wsa.contact
    private String name;      // Name of the person associated with the com.example.wsa.contact
    private String email;     // Email address
    private String subject;   // Subject of the com.example.wsa.contact message
    private String message;   // Actual message content

    // Additional methods (getters, setters, equals, hashCode, toString) are automatically generated by Lombok
}

